remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jakarta RESTful Web Services]
description: [Jakarta RESTful Web Services provides a specification document, TCK and foundational API to develop web services following the Representational State Transfer (REST) architectural pattern.]

latestVersion: 3.0.0

links:
  source: https://github.com/eclipse-ee4j/jaxrs-api
  javadocs: https://eclipse-ee4j.github.io/jaxrs-api/apidocs
  docs: https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html
  download: https://github.com/eclipse-ee4j/jaxrs-api/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/jaxrs-dev

